### ISSUE TITLE
webview version mismatch

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-deploy#274]
## Summary

We've run into a issue with the version.txt within webview. The problem arose because the intuitive thing to do from the DevOps perspective didn't match up with what actually happens. So we need to fix that.
It was believed that the webview tarball didn't need to be recreated since the tag from `v0.22.1rc4` is equal to `v0.22.1`. Thus, why rebuild it? Well, the problem is that the tarballs may be build from the same changeset but they come out with one significant difference, the contents of `version.txt`.

You can see an example of this:
```
$ http -b http://cnx.org/version.txt
v0.22.1rc4-dev74f5709
```

We are going to fix this minor difference by simply removing it. We will now be rendering the `version.txt` file during deployment instead of at build/compilation time.

### TODO

- [x] remove `version.txt` from the tarball build script (@philschatz)
- [ ] remove the `latest` and `latest-stable` symlinks from {builds,packages}.cnx.org (@DarkPrinceFrost | @dtwilliamson | @pumazi)
- [x] put a sha bit in the webview code, if possible; otherwise put it in a `rev.txt` (@philschatz)
- [x] remove the `latest` and `latest-stable` symlink creation from the build script (@philschatz)
- [x] remove tasks that use `latest*` in cnx-deploy (@pumazi | @DarkPrinceFrost | @dtwilliamson)
- [x] create tasks to render the `version.txt` in cnx-deploy (@pumazi | @DarkPrinceFrost | @dtwilliamson)

## Environment

all

**Comment by philschatz** [comment]
I had trouble using `git archive` to include the contents of the `dist/` directory it seems like it does not include files that are in `.gitignore`.

The commands I used were (from https://git-scm.com/docs/git-archive ):

```sh
mkdir ../deployment-testing
echo 'Last commit date: $Format:%cd by %aN$' > LAST_COMMIT
touch .gitattributes
git add LAST_COMMIT .gitattributes
git commit -am 'adding LAST_COMMIT file for archives'

mkdir ../deployment-testing
git archive HEAD dist/ | tar xCf ../deployment-testing -
```

Any ideas on what I'm doing wrong?

**Comment by pumazi** [comment]
@philschatz You have to put the file in `.gitattributes` with a directive type (e.g. [cnx-db .gitattributes](https://github.com/Connexions/cnx-db/blob/f5e9b1a2413252c3f9092f16918edeb5927d251e/.gitattributes)). I wouldn't think it would work with files that are in `.gitignore`, but I could be wrong.

**Comment by philschatz** [comment]
OK. I can probably fix the `.gitattributes` issue but I still don't know how to include the `./dist/` dir into the tarball... any idea how I could do that using `git archive`?

Or, is there a way to use `git` to write out a `LAST_COMMIT` file and then just use `tar ...` to create the tarball the same way it's done now?

**Comment by pumazi** [comment]
I don't know that you'll be able to include the `dist` dir. That's why I was hoping that we could potentially put the version number in the code itself. Then it would be available at build time in the code. So maybe something like:

1. include version template line in the code
1. modify the build script to use `git archive` before building
1. (optional) modify the dist creation script to write out the a `rev.json`

**Comment by philschatz** [comment]
Created a temp job: https://jenkins.cnx.org:8080/job/temp_Build_CNX_webview/ 

- This generates files named `_temp_webview...tar.gz` in https://packages.cnx.org/js-builds/ (check them to verify the `rev.txt` is correct)

**Comment by pumazi** [comment]
I don't recall whether we discussed a replacement for `latest` in regards to how to deploy the latest build to the `dev` environment. Right now we just pull the latest build during a deploy to `dev`. @philschatz, do you recall the solution for this case?

**Comment by philschatz** [comment]
I thought:

1. `latest` would be renamed to `master` (to clarify the term)
1. the `master` instance would redeploy when master changes either via polling, webhooks directly, or using webhooks indirectly (using a Jenkins job that just listens to pushes to `master`)

**Comment by pumazi** [comment]
@philschatz, that sounds good. You're going to need to make an adjustment to the Jenkins job to create the 'master' symlink.

**Comment by philschatz** [comment]
Since the name of the tarball is computed from the commit/tag, is it necessary to create a symlink?

Couldn't Jenkins just listen to changes in the master branch, check out `master` and compute the name of the tarball to use?

**Comment by pumazi** [comment]
Ok. Doesn't much mater to me, as long as it works. 👍

**Comment by reedstrm** [comment]
@phil, no if we don't create the symlink, there's no way to indicate in the ansible environment vars that you want tip-of-a-branch, since the name of the tarball will change with each commit. Forcing use of --extra-vars override for every deploy. Which doesn't even seem to work. Breaking the existing functionality without making the matching changes in the code that uses that functionality is rude.

**Comment by reedstrm** [comment]
To make it perfectly clear, the problem arises because v0.22.1rc4 was accepted, so a new tag of v0.22.1 was created for deployment, pointing at exactly the same commit, as is correct. Something in deployment decides if a tarball needs to be rebuilt from git based on the hash of commit under the tag. But our existing deployments read the included version.txt file, which _should_ change, even though none of the rest of the tarball does.

**Comment by karenc** [comment]
I think webview rev.txt is correct and we also have a new version.txt #397.
