### ISSUE TITLE
SEO Page load times: Optimizations from Google PageSpeed Insights Part 2: Electric Cachaloo

### ISSUE THREAD

**Issue by Dantemss** [Connexions/cnx-deploy#742]
Google PageSpeed Insights (https://developers.google.com/speed/pagespeed/insights/?url=cnx.org&tab=desktop) reports cnx.org is fast but low on optimizations. Go to Desktop (not mobile) -> Show Optimizations. Implementing more optimizations would further speed up our page load times.

# Impact
* **Severity**: [ ] High [x] Medium  [ ] Low
* **Frequency of Occurence**: [x] High [ ] Medium  [ ] Low

- (Complete) Enable browser caching headers for webview files and static files.
- (Complete) Add missing ETag headers to archive.
- (Complete) Clean up the varnish config so it defers caching to the backends.
- (Complete) Investigate if legacy/publishing/press are setting cache headers properly and if so remove the existing overrides in the varnish config.
- (Complete) Add hash to webview `dist` files, allowing us to set them to be cached forever.

# Next Steps for User
_If the card is accepted or rejected, what does user need to know now?_
If the card is rejected, performance would remain the same.

# PRs
Connexions/cnx-deploy#738
Connexions/cnx-deploy#740
Connexions/webview#1846
Connexions/cnx-archive#584
Connexions/cnx-archive#592
Connexions/cnx-press#193
Connexions/cnx-publishing#235
Connexions/cnx-deploy#782
Connexions/webview#1940
Connexions/cnx-deploy#783
Connexions/webview#1941
Connexions/cnx-deploy#786
Connexions/cnx-deploy#787

# Test Plan
- [x] All GET requests to CNX and subdomains should now come with a Cache-Control header (except legacy).
- [x] Webview assets (require.js, main.js) should have a hash as part of the filename and have Cache-Control set to 1 year. Notable exceptions: the current approach could not be applied to locale files (locale/dictionary.ftl) and settings.js.
- [ ] If during any testing you improperly get stale content (More than ~2 minutes old. For example, if you publish a new version of something and the content does not update within 2 minutes.) from any CNX or subdomain url, it may be caused by this card and may cause it to fail testing.

**Comment by kerwinso** [comment]
@Dantemss please update the description at the top of this issue with links to the related PRs, thanks.

**Comment by kerwinso** [comment]
Verified on qa, need to test on staging.

**Comment by kerwinso** [comment]
@Dantemss Looking at https://staging.cnx.org/contents/CImQfPDv@3.11:GfaWl1GG@4/Introduction, I see no Cache-Control headers for 302's in either incognito or non-incognito browsers:

![image](https://user-images.githubusercontent.com/11298165/45644788-2be9eb80-ba84-11e8-86fa-3020826e5c7d.png)

**Comment by kerwinso** [comment]
Dante says:
> not ideal, but I think at this point it's not a big enough issue to warrant any action on the release
...
> seems currently 302's are not getting cached and 301's are getting cached for only 1 minute
> ideally 302's would be cached for 1 minute and 301's would be cached forever

Maybe specific caching behavior for 301s and 302s can be part of a future issue/PR. But we're calling this issue good (per the Test Plan at top).
